import DAB_SMOTE
import numpy as np

class Visual_DAB(DAB_SMOTE.DAB_SMOTE):
    """
    A visualization and debugging extension of the DAB_SMOTE oversampling algorithm.

    This class inherits from :class:`DAB_SMOTE.DAB_SMOTE` and exposes internal
    debugging methods that are otherwise private in the parent class.
    It is intended for visualization, inspection, and step-by-step analysis of
    the synthetic data generation process.

    Parameters
    ----------
    **kwargs : dict
        Arbitrary keyword arguments passed to the parent class constructor
        (:class:`DAB_SMOTE.DAB_SMOTE`). See its documentation for details.

    Examples
    --------
    >>> from Visual_DAB import Visual_DAB
    >>> import numpy as np
    >>> X = np.random.rand(100, 2)
    >>> y = np.array([0]*90 + [1]*10)
    >>> visual = Visual_DAB()
    >>> X_res, y_res = visual.fit_resample(X, y)
    >>> visual.summary
    """

    def __init__(self, **kwargs):
        """
        Initialize a new instance of the Visual_DAB class.

        Parameters
        ----------
        **kwargs : dict
            Keyword arguments forwarded to the :class:`DAB_SMOTE.DAB_SMOTE` constructor.
        """
        super().__init__(**kwargs)

    def get_removed_samples(self, Xmin: np.ndarray) -> np.ndarray:
        """
        Return filtered minority samples after removing noise.

        This method is intended for debugging only. It exposes the internal
        noise removal process used in the DAB_SMOTE algorithm to identify and
        remove outliers from the minority class.

        Parameters
        ----------
        Xmin : np.ndarray
            Array containing minority class samples.

        Returns
        -------
        np.ndarray
            Filtered array of minority class samples with noisy instances removed.
        """
        return self._removeNoisySamples(Xmin)

    def get_clustering(self, Xmin: np.ndarray, solver: str = 'means') -> tuple[np.ndarray, np.ndarray]:
        """
        Return clustering results of the minority samples.

        Performs DBSCAN clustering on the minority class samples and
        computes cluster centers using the specified solver method.

        Parameters
        ----------
        Xmin : np.ndarray
            Minority class samples to be clustered.
        solver : {'means', 'density'}, default='means'
            Method to compute cluster centers. If 'means', centers are the mean
            of cluster points. If 'density', the densest point is used as the center.

        Returns
        -------
        tuple of (np.ndarray, np.ndarray)
            A tuple containing:
            - centers : np.ndarray
                Array of cluster centers.
            - clusters : np.ndarray
                Cluster label assigned to each sample.
        """
        self._solver = solver
        return self._clustering(Xmin)

    def get_screened_boundaries(self, Xmin: np.ndarray, clusters: np.ndarray) -> list[np.ndarray]:
        """
        Return detected boundary samples of the minority class clusters.

        Identifies boundary samples based on deviation from cluster means and
        standard deviations, which are used later to guide synthetic sample generation.

        Parameters
        ----------
        Xmin : np.ndarray
            Minority class samples.
        clusters : np.ndarray
            Array of cluster labels corresponding to each sample.

        Returns
        -------
        list of np.ndarray
            List containing arrays of boundary samples for each cluster.
        """
        return self._screenBoundarySamples(Xmin, clusters)

    def get_generated_samples(self, Xmin: np.ndarray, borders: list, clusters: np.ndarray, centers: np.ndarray, N: int) -> np.ndarray | None:
        """
        Return synthetic samples generated by the DAB_SMOTE algorithm.

        Generates new synthetic samples between boundary and cluster samples
        based on the interpolation and density-adaptive balancing mechanism of DAB_SMOTE.

        Parameters
        ----------
        Xmin : np.ndarray
            Minority class samples.
        borders : list of np.ndarray
            Boundary samples detected for each cluster.
        clusters : np.ndarray
            Cluster labels of the samples.
        centers : np.ndarray
            Centers of each cluster.
        N : int
            Number of new synthetic samples to generate.

        Returns
        -------
        np.ndarray or None
            Array of generated synthetic samples, or None if generation fails.
        """
        return self._generateNewSamples(Xmin, borders, clusters, centers, N)
